blueprint:
  homeassistant:
    min_version: 2024.10.0
  author: damru & hkfuertes
  domain: automation
  name: "[Z2M] IKEA Dual Button Remote - Light Control"
  description: |
    Control lights with IKEA RODRET, SOMRIG, TRADFRI or BILRESA remotes via Zigbee2MQTT: 
    - Press on/(1 dot) to turn on (optional brightness)
    - Press off/(2 dots) to turn off 
    - Hold on/(1 dot) to increase brightness
    - Hold off/(2 dots) to decrease to 1%.
  input:
    remote_devices:
      name: Remotes
      description: >
        IKEA remote (Rodret, Somrig, Tradfri, Bilresa) to use.
      default: []
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: RODRET wireless dimmer/power switch
            - integration: mqtt
              manufacturer: IKEA
              model: SOMRIG shortcut button
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI on/off switch
            - integration: mqtt
              manufacturer: IKEA
              model: BILRESA remote control with buttons
          multiple: true
    light:
      name: Light
      description: Light to control
      selector:
        entity:
          filter:
            domain: light
          multiple: false
    brightness_section:
      name: Brightness
      icon: mdi:lightbulb-on-50
      collapsed: true
      input:
        helper_force_brightness:
          name: Force brightness
          description: Force the brightness to **Brightness** value when light turns on.
          default: false
          selector:
            boolean: {}
        helper_brightness:
          name: Brightness
          description:
            Target light brightness when turning on. Requires **Force brightness**
            to be enabled.
          default: 50
          selector:
            number:
              unit_of_measurement: "%"
              min: 1.0
              max: 100.0
              step: 1.0
              mode: slider
mode: restart
max_exceeded: silent
triggers:
  # RODRET (E2201) - TRADFRI (E1743) - BILRESA(E2489)
  - trigger: mqtt
    topic: "+/+/action"
    payload: "on"
    id: press-on-z2m-e1743-e2201-E2489
  - trigger: mqtt
    topic: "+/+/action"
    payload: "off"
    id: press-off-z2m-e1743-e2201-E2489
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_move_up
    id: hold-on-z2m-e1743-e2201-E2489
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_move_down
    id: hold-off-z2m-e1743-e2201-E2489
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_stop
    id: release-z2m-e1743-e2201-E2489

  # SOMRIG - E2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_short_release
    id: press-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_short_release
    id: press-dots2-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_long_press
    id: hold-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_long_press
    id: hold-dots2-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_long_release
    id: release-hold-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_long_release
    id: release-hold-dots2-z2m-e2213
variables:
  helper_force_brightness: !input helper_force_brightness
  helper_hold_delay: 0.1
  helper_hold_dim_step: 4
  is_mqtt: "{{ trigger.platform == 'mqtt' }}"
  light: !input light
  mqtt_topic: "{{ trigger.topic }}"
  remote_devices: !input remote_devices
  remote_devices_names: "{{ remote_devices | map('device_attr', 'name') | list }}"
condition:
  - condition: template
    value_template: >-
      {{ 
        (trigger.topic.split('/')[1] in remote_devices_names if is_mqtt) 
      }}
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - press-on-z2m-e1743-e2201-E2489
              - press-dots1-z2m-e2213
        sequence:
          - choose:
              - conditions: "{{ helper_force_brightness }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light
                    data:
                      brightness_pct: !input helper_brightness
            default:
              - action: light.turn_on
                target:
                  entity_id: !input light
                data: {}
      - conditions:
          - condition: trigger
            id:
              - press-off-z2m-e1743-e2201-E2489
              - press-dots2-z2m-e2213
        sequence:
          - action: light.turn_off
            target:
              entity_id: !input light
            data: {}
      - conditions:
          - condition: trigger
            id:
              - hold-on-z2m-e1743-e2201-E2489
              - hold-dots1-z2m-e2213
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id:
                    - hold-on-z2m-e1743-e2201-E2489
                    - hold-dots1-z2m-e2213
              sequence:
                - parallel:
                    - action: light.turn_on
                      target:
                        entity_id: !input light
                      data:
                        brightness_step_pct: "{{ helper_hold_dim_step }}"
                        transition: "{{ helper_hold_delay }}"
                    - delay: "{{ helper_hold_delay }}"
      - conditions:
          - condition: trigger
            id:
              - hold-off-z2m-e1743-e2201-E2489
              - hold-dots2-z2m-e2213
        sequence:
          - variables:
              brightness_pct: "{{ iif(is_state(light, 'on'), state_attr(light, 'brightness'), 0) * 100 / 255 }}"
              total_iterations_to_zero: "{{ (brightness_pct / helper_hold_dim_step) | round(0, 'ceil') }}"
          - repeat:
              count: "{{ total_iterations_to_zero - 1 }}"
              sequence:
                - parallel:
                    - action: light.turn_on
                      target:
                        entity_id: !input light
                      data:
                        brightness_step_pct: "{{ helper_hold_dim_step | int * -1 }}"
                        transition: "{{ helper_hold_delay }}"
                    - delay: "{{ helper_hold_delay }}"
          - action: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_pct: 1
              transition: "{{ helper_hold_delay }}"